server:
  port: 8089
spring:
  application:
    name: webSecKillProvider
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://cdb-4tku65hf.gz.tencentcdb.com:10074/hbuy
    username: root
    password: 52f78d1584d775d70031c493bb1aee3c975c6d590a3f19d8bdf2b6d6b2b9d7d0!
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  redis:
    host: 192.168.0.193
    database: 0
    port: 6379
    password : 52f78d1584d775d70031c493bb1aee3c975c6d590a3f19d8bdf2b6d6b2b9d7d0
    timeout: 3000
  rabbitmq:
    virtual-host: /
    port: 5672
    host: 127.0.0.1
    username: guest
    password: guest
    connection-timeout: 3000
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 200
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.java.pojo

