server:
  port: 8090
spring:
  application:
    name: webHotProvider
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/hbuy
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    timeout: 3000
  rabbitmq:
    virtual-host: /
    port: 5672
    host: 127.0.0.1
    username: guest
    password: guest
    connection-timeout: 3000
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.java.pojo

