server:
  port: 8081

#为当前工程起服务名
spring:
  application:
    name: gbWeb
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://94.191.41.206:3306/hbuy
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10

#将此工工程对应的服务注册到注册中心上去
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.java.pojo





