server:
  port: 8086
spring:
  application:
    name: webHotProvider
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://94.191.41.206:3306/hbuy
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://94.191.41.206:3306/hbuy
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  redis:
    host: 94.191.41.206
    password: 123456
    database: 0
    port: 6379
    timeout: 3000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.java.pojo

